/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_gnaix_ndk_NativeMethod */

#ifndef _Included_com_example_gnaix_ndk_NativeMethod
#define _Included_com_example_gnaix_ndk_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_example_gnaix_ndk_NativeMethod
 * Method:    getInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL get_int(JNIEnv *, jclass, jint);

/*
 * Class:     com_example_gnaix_ndk_NativeMethod
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL get_string(JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_gnaix_ndk_NativeMethod
 * Method:    getByteArray
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL get_byteArray(JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_example_gnaix_ndk_NativeMethod
 * Method:    invokeJobject
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL invoke_Jobject(JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_example_gnaix_ndk_NativeMethod
 * Method:    invokeStaticFieldAndMethod
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL invoke_static_fieldAndMethod(JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_example_gnaix_ndk_NativeMethod
 * Method:    getPersons
 * Signature: ()[Lcom/example/gnaix/ndk/Person;
 */
JNIEXPORT jobjectArray JNICALL get_persons(JNIEnv *, jclass);

/*
 * Class:     com_example_gnaix_ndk_NativeMethod
 * Method:    callSuperInstanceMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL call_superInstance_method(JNIEnv *, jclass);


JNIEnv *g_env;
jclass native_class;

//注册函数数组
static JNINativeMethod methods[] = {
        {"getInt",                      "(I)I",                                   (void *)get_int},
        {"getString",                   "(Ljava/lang/String;)Ljava/lang/String;", (void *)get_string},
        {"getByteArray",                "([B)[B",                                 (void *)get_byteArray},
        {"invokeJobject",               "(Ljava/lang/String;I)V",                 (void *)invoke_Jobject},
        {"invokeStaticFieldAndMethod",  "(ILjava/lang/String;)V",                 (void *)invoke_static_fieldAndMethod},
        {"getPersons",                  "()[Lcom/example/gnaix/ndk/Person;",      (void *)get_persons},
        {"callSuperInstanceMethod",     "()V",                                    (void *)call_superInstance_method},
};
#ifdef __cplusplus
}
#endif
#endif
