/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_gnaix_ndk_NativeMethod */

#ifndef _Included_com_example_gnaix_ndk_NativeMethod
#define _Included_com_example_gnaix_ndk_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_gnaix_ndk_NativeMethod
 * Method:    getInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_gnaix_ndk_NativeMethod_getInt
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
